// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBVm3KdD57OXfUaGsqwd5TNFb7NyJFq1LU',
      appId: '1:807679916990:web:7d07f3fdff4f27b77457ef',
      messagingSenderId: '807679916990',
      projectId: 'android-task-monitoring-a7d9a',
      authDomain: 'android-task-monitoring-a7d9a.firebaseapp.com',
      databaseURL:
          'https://android-task-monitoring-a7d9a-default-rtdb.europe-west1.firebasedatabase.app',
      storageBucket: 'android-task-monitoring-a7d9a.appspot.com',
      measurementId: 'G-P5RG389SQ9',
      androidClientId:
          '807679916990-ni1koca7kl3b8jg5d3dh57gguoe8m1gi.apps.googleusercontent.com');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-lRpqo7h5fXFntfBMQNwG8ap4n-SHjV8',
    appId: '1:807679916990:android:4bbe198f274176cf7457ef',
    messagingSenderId: '807679916990',
    projectId: 'android-task-monitoring-a7d9a',
    databaseURL:
        'https://android-task-monitoring-a7d9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'android-task-monitoring-a7d9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdYNLn6aPKnvs7NwU4SdGmdWKyBU38Jg0',
    appId: '1:807679916990:ios:3800a92daf14a1ee7457ef',
    messagingSenderId: '807679916990',
    projectId: 'android-task-monitoring-a7d9a',
    databaseURL:
        'https://android-task-monitoring-a7d9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'android-task-monitoring-a7d9a.appspot.com',
    iosClientId:
        '807679916990-qsn1hf46gof05h28kuh6uoep1841653v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tyman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdYNLn6aPKnvs7NwU4SdGmdWKyBU38Jg0',
    appId: '1:807679916990:ios:3800a92daf14a1ee7457ef',
    messagingSenderId: '807679916990',
    projectId: 'android-task-monitoring-a7d9a',
    databaseURL:
        'https://android-task-monitoring-a7d9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'android-task-monitoring-a7d9a.appspot.com',
    iosClientId:
        '807679916990-qsn1hf46gof05h28kuh6uoep1841653v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tyman',
  );
}
